ROS#90 - Tasklet cyclic execution
n7space/aerugo pull request #17
Opened 2023-07-20 14:43 UTC by Glamhoth

2023-07-20 15:03 UTC, SteelPh0enix requested changes

2023-07-21 07:03 UTC, Glamhoth commented on src/aerugo.rs
> +        unsafe {
done

2023-07-21 07:03 UTC, Glamhoth commented on src/time_manager.rs
> +    /// This shoudln't be called in more than one place.
done, changed in `Executor` too

2023-07-21 07:08 UTC, SteelPh0enix approved these changes

2023-07-21 07:11 UTC, merged