ROS#94 - Timer driver implementation
n7space/aerugo pull request #24
Opened 2023-08-02 12:47 UTC by SteelPh0enix

Added HAL Timer driver implementation, with functionality for
- Timer and Channel clock management
- Channel chaining
- Channel triggering (per channel, or all at once)
- Channel enabling/disabling and mode switching (using typestate pattern)
- Interrupt configuration (to be expanded with fully featured interrupt handler)
- Channel registers management (basic, to be expanded)
- Waveform mode configuration (basic, to be expanded)

2023-08-02 14:01 UTC, Glamhoth requested changes

2023-08-02 14:01 UTC, Glamhoth commented on arch/cortex-m/samv71-hal/src/user_peripherals.rs
> +    pub timer_counter3: Option<pac::TC3>,
```suggestion
    /// Chip ID.
    pub chip_id: Option<pac::CHIPID>,
    /// Timer Counter 1.
    pub timer_counter1: Option<pac::TC1>,
    /// Timer Counter 2.
    pub timer_counter2: Option<pac::TC2>,
    /// Timer Counter 3.
    pub timer_counter3: Option<pac::TC3>,
```

2023-08-02 14:04 UTC, SteelPh0enix commented on arch/cortex-m/samv71-hal/src/drivers/timer.rs
> +            ExternalClock::XC2 => reg.modify(|_, w| unsafe { w.tc2xc2s().bits(clock_source_id) }),
the `?` is above, conversion function guarantees that either a valid value for this register will be returned, or nothing (which procs early return)

2023-08-02 14:05 UTC, SteelPh0enix commented on arch/cortex-m/samv71-hal/src/drivers/timer.rs
> +            ExternalClock::XC2 => reg.modify(|_, w| unsafe { w.tc2xc2s().bits(clock_source_id) }),
oh wait, i removed the `?` because i changed `Result` to `Option`, i'll fix that comment

2023-08-02 14:14 UTC, SteelPh0enix commented on arch/cortex-m/samv71-hal/src/drivers/timer.rs
> +    fn registers_ref(&self) -> &RegisterBlock {
moved

2023-08-02 14:16 UTC, SteelPh0enix commented on arch/cortex-m/samv71-hal/src/drivers/timer.rs
> +            ExternalClock::XC2 => reg.modify(|_, w| unsafe { w.tc2xc2s().bits(clock_source_id) }),
fixed the comment

2023-08-03 06:15 UTC, Glamhoth approved these changes

2023-08-03 06:16 UTC, merged